CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL
);

INSERT INTO categories (slug, name) VALUES ('uncategorized', 'Uncategorized');

ALTER TABLE products ADD COLUMN category_id BIGINT;
UPDATE products SET category_id = (SELECT id FROM categories WHERE slug = 'uncategorized');
ALTER TABLE products ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE products ADD CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id);

CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    sku VARCHAR(100) NOT NULL UNIQUE,
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    options_json TEXT NOT NULL DEFAULT '[]',
    option_signature TEXT NOT NULL,
    CONSTRAINT uq_variant_combination UNIQUE (product_id, option_signature),
    CONSTRAINT uq_variant_owner UNIQUE (product_id, id),
    CONSTRAINT ck_options_array CHECK (jsonb_typeof(options_json::jsonb) = 'array')
);

INSERT INTO product_variants (product_id, sku, price, active, options_json, option_signature)
SELECT id, sku, price, active, '[]', '[]' FROM products;

ALTER TABLE products ADD COLUMN default_variant_id BIGINT;
UPDATE products p SET default_variant_id = v.id FROM product_variants v WHERE v.product_id = p.id;
ALTER TABLE products ADD CONSTRAINT fk_products_default_variant
    FOREIGN KEY (id, default_variant_id) REFERENCES product_variants(product_id, id);

DROP INDEX uq_products_sku;
ALTER TABLE products DROP COLUMN sku;
ALTER TABLE products DROP COLUMN price;

CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_variants_product ON product_variants(product_id);
