ALTER TABLE carts
    ADD COLUMN customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
    ADD COLUMN currency VARCHAR(3),
    ADD CONSTRAINT uq_carts_customer UNIQUE (customer_id),
    ADD CONSTRAINT ck_carts_currency CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$');

ALTER TABLE cart_items DROP CONSTRAINT cart_items_pkey;
ALTER TABLE cart_items ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE cart_items ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);
ALTER TABLE cart_items ADD CONSTRAINT uq_cart_items_cart_variant UNIQUE (cart_id, variant_id);

CREATE INDEX idx_cart_items_cart ON cart_items(cart_id);
