CREATE TABLE customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    label VARCHAR(100),
    recipient_name VARCHAR(200) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    province VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    default_shipping BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_address_country CHECK (country_code ~ '^[A-Z]{2}$')
);
CREATE INDEX idx_addresses_customer ON customer_addresses(customer_id);
CREATE UNIQUE INDEX uq_addresses_default_shipping ON customer_addresses(customer_id) WHERE default_shipping;

ALTER TABLE carts
    ADD COLUMN shipping_recipient_name VARCHAR(200),
    ADD COLUMN shipping_phone VARCHAR(40),
    ADD COLUMN shipping_address_line1 VARCHAR(255),
    ADD COLUMN shipping_address_line2 VARCHAR(255),
    ADD COLUMN shipping_city VARCHAR(100),
    ADD COLUMN shipping_province VARCHAR(100),
    ADD COLUMN shipping_postal_code VARCHAR(20),
    ADD COLUMN shipping_country_code VARCHAR(2),
    ADD COLUMN shipping_method_code VARCHAR(50),
    ADD CONSTRAINT ck_shipping_snapshot CHECK (
        (shipping_recipient_name IS NULL AND shipping_phone IS NULL AND shipping_address_line1 IS NULL
         AND shipping_address_line2 IS NULL AND shipping_city IS NULL AND shipping_province IS NULL
         AND shipping_postal_code IS NULL AND shipping_country_code IS NULL AND shipping_method_code IS NULL)
        OR (shipping_recipient_name IS NOT NULL AND shipping_phone IS NOT NULL AND shipping_address_line1 IS NOT NULL
         AND shipping_city IS NOT NULL AND shipping_province IS NOT NULL AND shipping_postal_code IS NOT NULL
         AND shipping_country_code IS NOT NULL AND shipping_country_code ~ '^[A-Z]{2}$'));
